-- Run this in your Supabase project → SQL Editor
-- Adds new batting stat columns to batting_lines table

ALTER TABLE batting_lines
  ADD COLUMN IF NOT EXISTS sf   SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sac  SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fc   SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS roe  SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cs   SMALLINT NOT NULL DEFAULT 0;
